/**
 * Error codes chuẩn cho toàn hệ thống
 * Format: DOMAIN_DESCRIPTION
 */
export const ErrorCode = {
  // === Generic ===
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',

  // === Auth ===
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',

  // === User ===
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  USER_USERNAME_EXISTS: 'USER_USERNAME_EXISTS',

  // === IP Assets ===
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_NUMBER_EXISTS: 'ASSET_NUMBER_EXISTS',
  ASSET_TYPE_INVALID: 'ASSET_TYPE_INVALID',

  // === File Upload ===
  UPLOAD_FILE_TOO_LARGE: 'UPLOAD_FILE_TOO_LARGE',
  UPLOAD_FILE_TYPE_INVALID: 'UPLOAD_FILE_TYPE_INVALID',

  // === Reference Data ===
  REF_DISTRICT_NOT_FOUND: 'REF_DISTRICT_NOT_FOUND',
  REF_PROVINCE_NOT_FOUND: 'REF_PROVINCE_NOT_FOUND',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];